[versions]
gradle = "8.1.2"

kotlin = "1.9.20"
coreKtx = "1.12.0"
activity = "1.8.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
crypto = "1.0.0"
lottie = "6.4.1"
material = "1.11.0"
lifecycle = "2.5.1"
gson = "2.8.9"
retrofit = "2.9.0"

zoop = "1.3.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "crypto" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-ktx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

zoop-taponphone-debug = { group = "com.zoop.sdk", name = "taponphone-staging-debug", version.ref = "zoop" }
zoop-taponphone-release = { group = "com.zoop.sdk", name = "taponphone-production-release", version.ref = "zoop" }


[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
androidx-lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-viewmodel", "androidx-ktx-lifecycle-viewmodel"]
retrofit = ["retrofit", "retrofit-gson"]

